// Fantasy Leaderboard Data
export const leaderboard = [
  {
    userId: "user456",
    username: "cricketMaster99",
    rank: 1,
    totalPoints: 12560,
    contestsPlayed: 145,
    contestsWon: 32,
    earnings: 325000,
    avatar: "/images/avatars/user1.png",
    badges: ["legend", "champion", "hot streak"],
    teams: 478,
    previousRank: 2,
    winPercentage: 22.07
  },
  {
    userId: "user789",
    username: "fantasyCricketKing",
    rank: 2,
    totalPoints: 12345,
    contestsPlayed: 156,
    contestsWon: 28,
    earnings: 280000,
    avatar: "/images/avatars/user2.png",
    badges: ["veteran", "champion", "winner"],
    teams: 512,
    previousRank: 1,
    winPercentage: 17.95
  },
  {
    userId: "user234",
    username: "IPLMaster2023",
    rank: 3,
    totalPoints: 11980,
    contestsPlayed: 132,
    contestsWon: 25,
    earnings: 240000,
    avatar: "/images/avatars/user3.png",
    badges: ["rising star", "consistent"],
    teams: 396,
    previousRank: 5,
    winPercentage: 18.94
  },
  {
    userId: "user567",
    username: "cricketGenius",
    rank: 4,
    totalPoints: 11875,
    contestsPlayed: 128,
    contestsWon: 29,
    earnings: 235000,
    avatar: "/images/avatars/user4.png",
    badges: ["veteran", "winner"],
    teams: 384,
    previousRank: 3,
    winPercentage: 22.66
  },
  {
    userId: "user890",
    username: "fantasyPro",
    rank: 5,
    totalPoints: 11650,
    contestsPlayed: 140,
    contestsWon: 24,
    earnings: 210000,
    avatar: "/images/avatars/user5.png",
    badges: ["veteran", "consistent"],
    teams: 420,
    previousRank: 4,
    winPercentage: 17.14
  },
  {
    userId: "user123",
    username: "currentUser",
    rank: 1245,
    totalPoints: 5680,
    contestsPlayed: 85,
    contestsWon: 7,
    earnings: 25000,
    avatar: "/images/avatars/user6.png",
    badges: ["rookie"],
    teams: 255,
    previousRank: 1356,
    winPercentage: 8.24
  },
  {
    userId: "user345",
    username: "cricketWizard",
    rank: 6,
    totalPoints: 11325,
    contestsPlayed: 125,
    contestsWon: 22,
    earnings: 190000,
    avatar: "/images/avatars/user7.png",
    badges: ["veteran", "winner"],
    teams: 375,
    previousRank: 7,
    winPercentage: 17.60
  },
  {
    userId: "user678",
    username: "fantasyTiger",
    rank: 7,
    totalPoints: 11290,
    contestsPlayed: 130,
    contestsWon: 21,
    earnings: 185000,
    avatar: "/images/avatars/user8.png",
    badges: ["veteran", "consistent"],
    teams: 390,
    previousRank: 6,
    winPercentage: 16.15
  },
  {
    userId: "user901",
    username: "cricketStrategyExpert",
    rank: 8,
    totalPoints: 11180,
    contestsPlayed: 120,
    contestsWon: 20,
    earnings: 170000,
    avatar: "/images/avatars/user9.png",
    badges: ["veteran", "analyzer"],
    teams: 360,
    previousRank: 12,
    winPercentage: 16.67
  },
  {
    userId: "user234",
    username: "fantasySuperstar",
    rank: 9,
    totalPoints: 11050,
    contestsPlayed: 118,
    contestsWon: 19,
    earnings: 160000,
    avatar: "/images/avatars/user10.png",
    badges: ["veteran", "consistent"],
    teams: 354,
    previousRank: 8,
    winPercentage: 16.10
  },
  {
    userId: "user567",
    username: "cricketMegaFan",
    rank: 10,
    totalPoints: 10950,
    contestsPlayed: 115,
    contestsWon: 18,
    earnings: 155000,
    avatar: "/images/avatars/user11.png",
    badges: ["veteran", "winner"],
    teams: 345,
    previousRank: 9,
    winPercentage: 15.65
  }
]; 