// Cricket Teams Data
export const teams = [
  {
    id: 1,
    name: "Chennai Super Kings",
    shortName: "CSK",
    logo: "/images/teams/csk.png",
    primaryColor: "#FFFF00",
    secondaryColor: "#0081C8",
    captain: "MS Dhoni",
    homeGround: "M.A. Chidambaram Stadium",
    trophies: 5,
    description: "One of the most successful franchises in the league with a massive fan following.",
    players: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
  },
  {
    id: 2,
    name: "Mumbai Indians",
    shortName: "MI",
    logo: "/images/teams/mi.png",
    primaryColor: "#005DA0",
    secondaryColor: "#FFFFFF",
    captain: "Hardik Pandya",
    homeGround: "Wankhede Stadium",
    trophies: 5,
    description: "The most successful team in IPL history with a strong core of players.",
    players: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
  },
  {
    id: 3,
    name: "Royal Challengers Bangalore",
    shortName: "RCB",
    logo: "/images/teams/rcb.png",
    primaryColor: "#EC1C24",
    secondaryColor: "#000000",
    captain: "Faf du Plessis",
    homeGround: "M. Chinnaswamy Stadium",
    trophies: 0,
    description: "Known for their strong batting lineup and passionate fan base.",
    players: [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
  },
  {
    id: 4,
    name: "Kolkata Knight Riders",
    shortName: "KKR",
    logo: "/images/teams/kkr.png",
    primaryColor: "#3A225D",
    secondaryColor: "#FDB80C",
    captain: "Shreyas Iyer",
    homeGround: "Eden Gardens",
    trophies: 2,
    description: "A dynamic team known for their aggressive style of play.",
    players: [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
  },
  {
    id: 5,
    name: "Delhi Capitals",
    shortName: "DC",
    logo: "/images/teams/dc.png",
    primaryColor: "#00008B",
    secondaryColor: "#FF0000",
    captain: "Rishabh Pant",
    homeGround: "Arun Jaitley Stadium",
    trophies: 0,
    description: "A team filled with young talent and experienced internationals.",
    players: [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55],
  },
  {
    id: 6,
    name: "Punjab Kings",
    shortName: "PBKS",
    logo: "/images/teams/pbks.png",
    primaryColor: "#ED1C24",
    secondaryColor: "#CCCCCC",
    captain: "Shikhar Dhawan",
    homeGround: "PCA Stadium",
    trophies: 0,
    description: "Known for their explosive batting and aggressive strategies.",
    players: [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66],
  },
  {
    id: 7,
    name: "Rajasthan Royals",
    shortName: "RR",
    logo: "/images/teams/rr.png",
    primaryColor: "#254AA5",
    secondaryColor: "#FF1744",
    captain: "Sanju Samson",
    homeGround: "Sawai Mansingh Stadium",
    trophies: 1,
    description: "The inaugural champions known for their smart auction strategies.",
    players: [67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77],
  },
  {
    id: 8,
    name: "Sunrisers Hyderabad",
    shortName: "SRH",
    logo: "/images/teams/srh.png",
    primaryColor: "#FF822A",
    secondaryColor: "#000000",
    captain: "Pat Cummins",
    homeGround: "Rajiv Gandhi International Cricket Stadium",
    trophies: 1,
    description: "Known for their strong bowling attack and balanced team.",
    players: [78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88],
  },
  {
    id: 9,
    name: "Gujarat Titans",
    shortName: "GT",
    logo: "/images/teams/gt.png",
    primaryColor: "#1D3C99",
    secondaryColor: "#FFCF40",
    captain: "Shubman Gill",
    homeGround: "Narendra Modi Stadium",
    trophies: 1,
    description: "The newest franchise that made an immediate impact in the league.",
    players: [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
  },
  {
    id: 10,
    name: "Lucknow Super Giants",
    shortName: "LSG",
    logo: "/images/teams/lsg.png",
    primaryColor: "#A72056",
    secondaryColor: "#FFAC12",
    captain: "KL Rahul",
    homeGround: "BRSABV Ekana Cricket Stadium",
    trophies: 0,
    description: "One of the newest teams with a mix of experienced and young players.",
    players: [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
  },
]; 